import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions governing the use of SoloLedger financial tools.',
  alternates: { canonical: '/terms' },
};

export default function TermsPage() {
  const lastUpdated = 'August 25, 2026';

  return (
    <main className="min-h-screen bg-slate-50 px-6 py-16 md:px-12 lg:px-24">
      <div className="mx-auto max-w-4xl rounded-3xl border border-slate-200 bg-white p-8 md:p-14 shadow-xs">
        <h1 className="text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-xs font-semibold uppercase tracking-wider text-slate-400">
          Last Updated: {lastUpdated}
        </p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-slate-600">
          <section>
            <h2 className="text-lg font-bold text-slate-900">1. Acceptance of Terms</h2>
            <p className="mt-2">
              By accessing, browsing, or utilizing any calculators, tools, invoice makers, or benchmarking materials on <Link href="/" className="text-blue-600 underline">solo-ledger.com</Link> (&quot;SoloLedger&quot;), you acknowledge that you have read, understood, and agree to be legally bound by these Terms of Service. If you do not agree, you must discontinue use immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900">2. Permitted Use & Intellectual Property</h2>
            <p className="mt-2">
              SoloLedger grants you a limited, revocable, non-exclusive, non-transferable license to use our web utilities for personal or commercial business planning. You agree not to:
            </p>
            <ul className="mt-2 list-disc pl-5 space-y-1">
              <li>Reverse engineer, scrape, extract, or republish our algorithmic rate engines and dataset without express written consent.</li>
              <li>Use automated bots, spiders, or scrapers to generate unnatural load on our infrastructure.</li>
              <li>Impersonate SoloLedger or misrepresent calculations generated by this site as certified financial audits.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900">3. Accuracy of Calculations & No Warranty</h2>
            <p className="mt-2">
              All tools, formulas, tax estimates (including Self-Employment tax and W-2/1099 conversions), and industry rate benchmarks are provided strictly on an <strong>&quot;AS IS&quot;</strong> and <strong>&quot;AS AVAILABLE&quot;</strong> basis without warranties of any kind, whether express or implied. Tax rates, deductions, and financial rules change across jurisdictions; SoloLedger makes no guarantee regarding the absolute legal or financial accuracy of the output.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900">4. Third-Party Links & Services</h2>
            <p className="mt-2">
              Our website contains links and promotional cards to third-party platforms (such as FreshBooks, Wise, and Deel). We do not control, operate, or assume responsibility for the content, privacy practices, billing, or services provided by third-party providers. Your interactions with third-party software are governed strictly by their respective terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900">5. Limitation of Liability</h2>
            <p className="mt-2">
              In no event shall SoloLedger, its founders, operators, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages—including loss of revenue, tax penalties, client disputes, or data discrepancies—resulting from your reliance on our tools or content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900">6. Modifications to Terms</h2>
            <p className="mt-2">
              We reserve the right to modify these Terms at any time. Continued use of the platform after updates constitutes binding acceptance of the modified Terms.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}