export interface RateInputs {
  /**
   * Desired annual take-home income after taxes and business expenses.
   */
  targetNetIncome: number;

  /**
   * Annual business expenses such as:
   * software, equipment, insurance, accounting, marketing, etc.
   */
  annualExpenses: number;

  /**
   * Average number of hours per week that clients actually pay for.
   */
  billableHoursPerWeek: number;

  /**
   * Number of weeks per year the freelancer does not expect
   * to generate billable client revenue.
   */
  vacationWeeks: number;

  /**
   * Estimated combined effective tax rate.
   *
   * Example:
   * 28 = 28%
   */
  taxRate: number;
}

export interface RateResult {
  /**
   * Absolute minimum hourly rate required to hit the financial target
   * based strictly on the supplied assumptions.
   */
  minHourlyRate: number;

  /**
   * Recommended hourly rate including the built-in business cushion.
   */
  recommendedHourlyRate: number;

  /**
   * Recommended 8-hour day rate.
   */
  dayRate: number;

  /**
   * Gross annual revenue required before taxes and expenses.
   */
  annualGrossTarget: number;

  /**
   * Total number of client-billable hours expected during the year.
   */
  totalAnnualBillableHours: number;

  /**
   * Desired monthly take-home income.
   */
  monthlyTakeHome: number;

  /**
   * Estimated annual taxes based on the effective tax rate.
   */
  estimatedAnnualTaxes: number;

  /**
   * Estimated monthly gross revenue target.
   */
  monthlyGrossTarget: number;

  /**
   * Estimated weekly gross revenue target during working weeks.
   */
  weeklyGrossTarget: number;

  /**
   * Recommended monthly revenue generated by the recommended rate.
   */
  recommendedMonthlyRevenue: number;

  /**
   * Recommended annual revenue generated by the recommended rate.
   */
  recommendedAnnualRevenue: number;

  /**
   * Extra annual revenue created by the recommended safety margin.
   */
  annualSafetyMargin: number;

  /**
   * Percentage of a traditional 40-hour work week represented by
   * the user's billable hours.
   */
  billableUtilization: number;

  /**
   * Number of working weeks in the year after vacation.
   */
  workingWeeks: number;

  /**
   * Estimated weekly take-home income.
   */
  weeklyTakeHome: number;
}

/**
 * Safely round a number up to the nearest whole dollar.
 */
function roundUp(value: number): number {
  return Math.ceil(Math.max(0, value));
}

/**
 * Safely round a number to the nearest dollar.
 */
function roundNearest(value: number): number {
  return Math.round(Math.max(0, value));
}

/**
 * Clamp a value between a minimum and maximum.
 */
function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

export function computeFreelanceRate(inputs: RateInputs): RateResult {
  /*
   * ---------------------------------------------------------------
   * 1. SANITIZE INPUTS
   * ---------------------------------------------------------------
   *
   * This prevents negative values or impossible percentages from
   * producing broken calculations.
   */

  const targetNetIncome = Math.max(0, inputs.targetNetIncome);

  const annualExpenses = Math.max(0, inputs.annualExpenses);

  const billableHoursPerWeek = clamp(
    Number(inputs.billableHoursPerWeek) || 0,
    0,
    168,
  );

  const vacationWeeks = clamp(
    Number(inputs.vacationWeeks) || 0,
    0,
    51,
  );

  /*
   * We prevent the tax rate from reaching 100%.
   *
   * At 100%, the gross revenue equation would become undefined.
   */
  const taxRate = clamp(Number(inputs.taxRate) || 0, 0, 95);

  /*
   * ---------------------------------------------------------------
   * 2. WORKING WEEKS
   * ---------------------------------------------------------------
   */

  const workingWeeks = Math.max(1, 52 - vacationWeeks);

  /*
   * ---------------------------------------------------------------
   * 3. ANNUAL BILLABLE CAPACITY
   * ---------------------------------------------------------------
   */

  const totalAnnualBillableHours =
    workingWeeks * billableHoursPerWeek;

  /*
   * ---------------------------------------------------------------
   * 4. REQUIRED GROSS REVENUE
   * ---------------------------------------------------------------
   *
   * Example:
   *
   * Take-home goal = $80,000
   * Expenses       = $10,000
   * Tax rate       = 28%
   *
   * Gross required:
   *
   * ($80,000 + $10,000) / (1 - .28)
   *
   * = $125,000
   *
   * This means approximately $125k of revenue is required to
   * support the target under the supplied assumptions.
   */

  const taxableBase =
    targetNetIncome + annualExpenses;

  const taxMultiplier =
    1 - taxRate / 100;

  const grossNeeded =
    taxMultiplier > 0
      ? taxableBase / taxMultiplier
      : taxableBase;

  /*
   * ---------------------------------------------------------------
   * 5. MINIMUM HOURLY RATE
   * ---------------------------------------------------------------
   */

  const rawHourly =
    totalAnnualBillableHours > 0
      ? grossNeeded / totalAnnualBillableHours
      : 0;

  const minHourlyRate = roundUp(rawHourly);

  /*
   * ---------------------------------------------------------------
   * 6. RECOMMENDED RATE
   * ---------------------------------------------------------------
   *
   * The 20% margin is intentionally applied to the rate.
   *
   * This represents additional protection against:
   *
   * - slow client pipelines
   * - scope creep
   * - unpaid communication
   * - sales time
   * - cancellations
   * - payment delays
   * - unexpected administrative work
   *
   * Importantly, this is now reflected in the recommended annual
   * revenue as well, keeping the model internally consistent.
   */

  const safetyMultiplier = 1.2;

  const recommendedHourlyRate = roundUp(
    minHourlyRate * safetyMultiplier,
  );

  /*
   * ---------------------------------------------------------------
   * 7. RECOMMENDED REVENUE
   * ---------------------------------------------------------------
   */

  const recommendedAnnualRevenue = roundNearest(
    recommendedHourlyRate * totalAnnualBillableHours,
  );

  const annualSafetyMargin = Math.max(
    0,
    recommendedAnnualRevenue - roundNearest(grossNeeded),
  );

  /*
   * ---------------------------------------------------------------
   * 8. DAY RATE
   * ---------------------------------------------------------------
   *
   * Standard 8-hour equivalent.
   */

  const dayRate = roundUp(
    recommendedHourlyRate * 8,
  );

  /*
   * ---------------------------------------------------------------
   * 9. MONTHLY / WEEKLY TARGETS
   * ---------------------------------------------------------------
   */

  const monthlyGrossTarget = roundNearest(
    grossNeeded / 12,
  );

  const weeklyGrossTarget = roundNearest(
    grossNeeded / workingWeeks,
  );

  const recommendedMonthlyRevenue = roundNearest(
    recommendedAnnualRevenue / 12,
  );

  const monthlyTakeHome = roundNearest(
    targetNetIncome / 12,
  );

  const weeklyTakeHome = roundNearest(
    targetNetIncome / workingWeeks,
  );

  /*
   * ---------------------------------------------------------------
   * 10. TAX ESTIMATE
   * ---------------------------------------------------------------
   *
   * This remains an estimate based on the user's supplied effective
   * tax rate. It is NOT intended to represent an actual tax return.
   */

  const estimatedAnnualTaxes = roundNearest(
    grossNeeded * (taxRate / 100),
  );

  /*
   * ---------------------------------------------------------------
   * 11. BILLABLE UTILIZATION
   * ---------------------------------------------------------------
   *
   * We compare billable hours against a traditional 40-hour week.
   *
   * Example:
   *
   * 25 billable hours / 40 total hours = 62.5%
   */

  const billableUtilization = roundNearest(
    (billableHoursPerWeek / 40) * 100,
  );

  /*
   * ---------------------------------------------------------------
   * 12. RETURN
   * ---------------------------------------------------------------
   */

  return {
    minHourlyRate,
    recommendedHourlyRate,
    dayRate,

    annualGrossTarget: roundNearest(grossNeeded),

    totalAnnualBillableHours,

    monthlyTakeHome,

    estimatedAnnualTaxes,

    monthlyGrossTarget,

    weeklyGrossTarget,

    recommendedMonthlyRevenue,

    recommendedAnnualRevenue,

    annualSafetyMargin,

    billableUtilization,

    workingWeeks,

    weeklyTakeHome,
  };
}